package io.github.spair.repoxbot.constant

const val ACTION = "action"
const val PULL_REQUEST = "pull_request"
const val MERGED = "merged"
const val ISSUE = "issue"
const val CONTENT = "content"
const val SHA = "sha"
const val MESSAGE = "message"
const val PATH = "path"
const val BODY = "body"
const val TITLE = "title"
const val NUMBER = "number"
const val USER = "user"
const val LOGIN = "login"
const val HTML_URL = "html_url"
const val DIFF_URL = "diff_url"
const val NAME = "name"
const val FILENAME = "filename"
const val STATUS = "status"
const val RAW_URL = "raw_url"
const val ID = "id"
const val HEAD = "head"
const val REF = "ref"
const val LABELS = "labels"
const val LABEL = "label"
const val SENDER = "sender"
